-- CREATE USER "nwtis_1" PASSWORD "nwtis#1"
-- SELECT * FROM INFORMATION_SCHEMA.SYSTEM_USERS;

--SELECT * FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES;



GRANT SELECT, UPDATE, INSERT ON TABLE dnevnik_Rada TO aplikacija;