CREATE TABLE korisnici (
	korisnik VARCHAR(20) NOT NULL,
	ime VARCHAR(25),
	prezime VARCHAR(25),
	lozinka VARCHAR(20),
	email VARCHAR(100),
	PRIMARY KEY (korisnik)
);

CREATE TABLE grupe (
	grupa VARCHAR(20) NOT NULL,
	naziv VARCHAR(55),
	PRIMARY KEY (grupa)
);

CREATE TABLE uloge (
	korisnik VARCHAR(20) NOT NULL,
	grupa VARCHAR(20) NOT NULL,
	PRIMARY KEY (korisnik, grupa),
	FOREIGN KEY (korisnik) REFERENCES korisnici (korisnik),
	FOREIGN KEY (grupa) REFERENCES grupe (grupa)
);

GRANT SELECT, UPDATE, INSERT ON TABLE korisnici TO "aplikacija";
GRANT SELECT, UPDATE, INSERT ON TABLE grupe TO "aplikacija";
GRANT SELECT, UPDATE, INSERT ON TABLE uloge TO "aplikacija";

CREATE TABLE partneri (
	id integer NOT NULL,
	naziv VARCHAR(255),
	vrstaKuhinje VARCHAR(2) NOT NULL,
	adresa VARCHAR(255) NOT NULL,
	mreznaVrata integer NOT NULL,
	mreznaVrataKraj integer NOT NULL,
	gpsSirina float NOT NULL,
	gpsDuzina float NOT NULL,
	sigurnosniKod VARCHAR(20) NOT NULL,
	adminKod VARCHAR(20) NOT NULL,
	PRIMARY KEY (id)
)

CREATE TABLE obracuni (
	rb int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	partner integer NOT NULL,
	id VARCHAR(2) NOT NULL,
	jelo boolean NOT NULL,
	kolicina float NOT NULL,
	cijena float NOT NULL,
	gpsSirina float NOT NULL,
	gpsDuzina float NOT NULL,
	sigurnosniKod VARCHAR(20) NOT NULL,
	vrijeme TIMESTAMP NOT NULL,
	FOREIGN KEY (partner) REFERENCES partneri (id)
)

GRANT SELECT, UPDATE, INSERT ON TABLE partneri TO "aplikacija";
GRANT SELECT, UPDATE, INSERT ON TABLE obracuni TO "aplikacija";
