CREATE SEQUENCE ZAPISI_ID AS INTEGER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OBRACUNI_ID AS INTEGER START WITH 1 INCREMENT BY 1;
GRANT ALL ON SEQUENCE ZAPISI_ID TO "aplikacija";
GRANT ALL ON SEQUENCE OBRACUNI_ID TO "aplikacija";

create table zapisi (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	vrijeme timestamp,
	korisnickoIme char (20),
	adresaRacunala varchar (99),
	ipAdresaRacunala varchar (50),
	opisRada varchar (1024)
); 

GRANT SELECT, UPDATE, INSERT ON TABLE zapisi TO "aplikacija";

